version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Maven build
          command: mvnw.cmd clean install

      - run:
          name: Print the Current Time
          command: date
